services:
  - type: web
    name: tripsync-backend
    env: python
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: bash render_build.sh
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: tripsync
      - key: JWT_SECRET
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        value: $PORT
      - key: GROQ_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: MQTT_BROKER
        value: broker.hivemq.com
      - key: MQTT_PORT
        value: 1883
